name: Rust

on: [push]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
  build_osx:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install_dependencies
        run: |
          brew install SDL2
          brew install rustup
          rustup-init -y --default-toolchain stable
      - name: Build
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo build